# Generated by Django 4.2.5 on 2023-09-18 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domicilio',
            options={'verbose_name': 'domicilio', 'verbose_name_plural': 'domicilios'},
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cuit', models.CharField(max_length=11, verbose_name='cuit')),
                ('email', models.EmailField(default='ejemplo@gmail.com', max_length=250, unique=True)),
                ('dom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.domicilio')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
