# Generated by Django 4.2.5 on 2023-09-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_domicilio_options_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dom',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='dom',
        ),
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(default=' ', max_length=25, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=' ', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(default=' ', max_length=20, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='prov',
            field=models.CharField(default=' ', max_length=50, verbose_name='Provincia'),
        ),
        migrations.DeleteModel(
            name='domicilio',
        ),
    ]
