# Generated by Django 4.2.5 on 2023-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='empresa/', verbose_name='Foto 4x4'),
        ),
    ]
