# Generated by Django 4.2.5 on 2023-10-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_empresa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='media/imagenes/', verbose_name='Foto 4x4'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='media/imagenes/', verbose_name='Logo'),
        ),
    ]
