# Generated by Django 4.2.5 on 2023-10-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_foto_alter_empresa_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(default='ejemplo@gmail.com', max_length=250, unique=True)),
                ('mensaje', models.TextField(max_length=250)),
            ],
        ),
    ]
